# Generated by Django 5.0.1 on 2024-01-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='puntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePV', models.CharField(max_length=40, verbose_name='Nombre del Punto de Venta')),
                ('direccionPV', models.CharField(max_length=40, verbose_name='Dirección del Punto de Venta')),
                ('telefonoPV', models.IntegerField(max_length=10, verbose_name='Teléfono del Punto de Venta')),
            ],
        ),
        migrations.AddField(
            model_name='articulosmodel',
            name='cantidadMayoreo',
            field=models.FloatField(default=2, verbose_name='Cantidad a partir de la cual se cuenta como mayoreo'),
        ),
        migrations.AddField(
            model_name='articulosmodel',
            name='sucursal',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre de la sucursal'),
        ),
    ]
