# Generated by Django 5.0.1 on 2024-01-28 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0002_puntoventa_articulosmodel_cantidadmayoreo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articulosmodel',
            name='precioVentaProveedor',
        ),
        migrations.AddField(
            model_name='articulosmodel',
            name='precioVentaVendedorReparto',
            field=models.FloatField(default=99999, verbose_name='Precio de venta al vendedor de reparto'),
        ),
        migrations.AddField(
            model_name='articulosmodel',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulosmodel',
            name='unidad',
            field=models.CharField(default='Caja', max_length=200, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='telefonoPV',
            field=models.IntegerField(verbose_name='Teléfono del Punto de Venta'),
        ),
        migrations.CreateModel(
            name='stockPuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.articulosmodel')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.puntoventa')),
            ],
        ),
    ]
