# Generated by Django 5.0.1 on 2024-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0003_producto_remove_articulosmodel_precioventaproveedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.RemoveField(
            model_name='articulosmodel',
            name='cantidadArticulo',
        ),
        migrations.RemoveField(
            model_name='articulosmodel',
            name='sucursal',
        ),
        migrations.AlterField(
            model_name='articulosmodel',
            name='nombreArticulo',
            field=models.CharField(max_length=100, verbose_name='Nombre del artículo'),
        ),
        migrations.AlterField(
            model_name='articulosmodel',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock actual'),
        ),
    ]
