# Generated by Django 5.0.1 on 2024-01-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0006_remove_articulosmodel_cantidadmayoreo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulosmodel',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockpuntoventa',
            unique_together={('sucursal', 'producto')},
        ),
    ]
