# Generated by Django 5.0.1 on 2024-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0009_sales_remove_venta_punto_venta_salesitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpuntoventa',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
