# Generated by Django 5.0.1 on 2024-02-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0013_sellersales_sellerinventory_fecha_sellersalesitems'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerinventory',
            unique_together={('product_id', 'seller_id')},
        ),
    ]
