# Generated by Django 5.0.1 on 2024-02-23 21:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0014_alter_sellerinventory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photos/'),
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha:'),
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='precioOriginal',
            field=models.FloatField(default=0, verbose_name='Costo para BECAANA'),
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='precioVentaVendedor',
            field=models.FloatField(default=0, verbose_name='Precio de venta para vendedor'),
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.articulosmodel', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='qty',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.seller', verbose_name='Vendedor'),
        ),
    ]
