# Generated by Django 5.0.1 on 2024-02-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0015_seller_photo_alter_sellerinventory_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersales',
            name='seller_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.seller', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='sellersalesitems',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.sales'),
        ),
    ]
