# Generated by Django 5.0.1 on 2024-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0016_sellersales_seller_id_alter_sellersalesitems_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinventory',
            name='nombreArticulo',
            field=models.CharField(default=0, max_length=100, verbose_name='Nombre del artículo'),
            preserve_default=False,
        ),
    ]
