# Generated by Django 5.0.1 on 2024-02-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0017_sellerinventory_nombrearticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='puntoVenta',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.puntoventa'),
            preserve_default=False,
        ),
    ]
