# Generated by Django 5.0.1 on 2024-02-24 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0018_sales_puntoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='puntoVenta',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.puntoventa'),
        ),
    ]
