# Generated by Django 5.0.1 on 2024-02-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0019_alter_sales_puntoventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='puntoVenta',
        ),
    ]
