# Generated by Django 5.0.1 on 2024-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0020_remove_sales_puntoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='nuevoCampoinutil',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
