# Generated by Django 5.0.1 on 2024-02-24 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0022_remove_sales_nuevocampoinutil'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sucursal',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.puntoventa'),
            preserve_default=False,
        ),
    ]
