# Generated by Django 5.0.1 on 2024-02-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0023_sales_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sucursal',
        ),
    ]
