# Generated by Django 5.0.1 on 2024-02-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0024_remove_sales_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersales',
            name='seller_id',
        ),
    ]
