# Generated by Django 5.0.1 on 2024-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0025_remove_sellersales_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='origen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Origen de la venta:'),
        ),
    ]
