# Generated by Django 5.0.1 on 2024-02-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0026_sales_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='origen',
        ),
    ]
