# Generated by Django 5.0.1 on 2024-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0029_sales_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersales',
            name='origin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
