# Generated by Django 5.0.1 on 2024-03-17 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0030_sellersales_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='costosEmpresaPuntosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarios', models.FloatField(default=213.39)),
                ('productos', models.FloatField(default=0)),
                ('otros', models.FloatField(default=0)),
                ('puntoVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.puntoventa')),
            ],
        ),
        migrations.CreateModel(
            name='costosEmpresaVendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.FloatField(default=213.39)),
                ('gasolina', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('otros', models.FloatField(default=0)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.seller')),
            ],
        ),
    ]
