# Generated by Django 5.0.1 on 2024-03-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0032_costosempresapuntosventa_fecha_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='costosEmpresaPuntosVenta',
            new_name='costosEmpresaPuntosVentaModel',
        ),
        migrations.RenameModel(
            old_name='costosEmpresaVendedores',
            new_name='costosEmpresaVendedoresModel',
        ),
    ]
