# Generated by Django 5.0.1 on 2024-03-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0033_rename_costosempresapuntosventa_costosempresapuntosventamodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costosempresavendedoresmodel',
            name='total',
        ),
    ]
