# Generated by Django 5.0.1 on 2024-03-27 22:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0034_remove_costosempresavendedoresmodel_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(verbose_name='Identificador del usuario')),
                ('tipo', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Punto de Venta', 'Punto de Venta')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='costosempresapuntosventamodel',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de los costos'),
        ),
        migrations.AlterField(
            model_name='costosempresapuntosventamodel',
            name='otros',
            field=models.FloatField(default=0, verbose_name='Otros gastos'),
        ),
        migrations.AlterField(
            model_name='costosempresapuntosventamodel',
            name='productos',
            field=models.FloatField(default=0, verbose_name='Gastado en Adquisición de mercancía'),
        ),
        migrations.AlterField(
            model_name='costosempresapuntosventamodel',
            name='puntoVenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.puntoventa', verbose_name='Nombre del punto de venta'),
        ),
        migrations.AlterField(
            model_name='costosempresapuntosventamodel',
            name='salarios',
            field=models.FloatField(default=0, verbose_name='Salarios de los trabajadores'),
        ),
        migrations.AlterField(
            model_name='costosempresavendedoresmodel',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de los costos'),
        ),
        migrations.AlterField(
            model_name='costosempresavendedoresmodel',
            name='gasolina',
            field=models.FloatField(default=0, verbose_name='Dinero otorgado para gasolinas:'),
        ),
        migrations.AlterField(
            model_name='costosempresavendedoresmodel',
            name='otros',
            field=models.FloatField(default=0, verbose_name='Otros gastos'),
        ),
        migrations.AlterField(
            model_name='costosempresavendedoresmodel',
            name='salario',
            field=models.FloatField(default=213.39, verbose_name='Salario del vendedor:'),
        ),
        migrations.AlterField(
            model_name='costosempresavendedoresmodel',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.seller', verbose_name='Nombre del vendedor al que se le dá'),
        ),
    ]
