# Generated by Django 5.0.1 on 2024-03-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0038_alter_stockpuntoventa_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosempresavendedoresmodel',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.seller', verbose_name='Nombre del vendedor al que se le dá'),
        ),
        migrations.AlterField(
            model_name='stockpuntoventa',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.puntoventa'),
        ),
    ]
