# Generated by Django 5.0.1 on 2024-03-29 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0039_alter_costosempresavendedoresmodel_vendedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pvInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioVentaVendedor', models.FloatField(default=0, verbose_name='Precio de venta para vendedor')),
                ('qty', models.FloatField(default=0, verbose_name='Cantidad')),
                ('precioOriginal', models.FloatField(default=0, verbose_name='Costo para BECAANA')),
                ('nombreArticulo', models.CharField(max_length=100, verbose_name='Nombre del artículo')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha:')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becaanaPVm1APP1.articulosmodel', verbose_name='Producto')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Punto de venta:')),
            ],
            options={
                'unique_together': {('product_id', 'seller_id')},
            },
        ),
    ]
