# Generated by Django 5.0.1 on 2024-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0042_alter_costosempresapuntosventamodel_puntoventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosmodel',
            name='cantidad',
            field=models.FloatField(default=0, verbose_name='Stock maestro'),
            preserve_default=False,
        ),
    ]
