# Generated by Django 5.0.1 on 2024-04-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0044_registroinventariovendedores'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerinventory',
            unique_together=set(),
        ),
    ]
