# Generated by Django 5.0.1 on 2024-04-14 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0045_alter_sellerinventory_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerinventory',
            unique_together={('product_id', 'seller_id')},
        ),
    ]
