# Generated by Django 5.0.1 on 2024-04-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0046_alter_sellerinventory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersalesitems',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
