# Generated by Django 5.0.1 on 2024-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0047_sellersalesitems_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesitemspv',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
