# Generated by Django 5.0.1 on 2024-04-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0049_registroinventariopuntoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosmodel',
            name='cantidadStockMaestro',
            field=models.FloatField(default=0, verbose_name='Cantidad en STOCK dentro de matriz'),
            preserve_default=False,
        ),
    ]
