# Generated by Django 5.0.1 on 2024-04-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0050_articulosmodel_cantidadstockmaestro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulosmodel',
            name='cantidadStockMaestro',
        ),
    ]
