# Generated by Django 5.0.1 on 2024-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0051_remove_articulosmodel_cantidadstockmaestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosmodel',
            name='precioVentaVendeedorExterno',
            field=models.FloatField(default=0, verbose_name='Precio de venta al vendedor externo'),
        ),
    ]
