# Generated by Django 5.0.1 on 2024-04-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0053_rename_precioventavendeedorexterno_articulosmodel_precioventavendedorexterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_externalSeller', models.BooleanField(default=False)),
                ('is_matrixSeller', models.BooleanField(default=False)),
            ],
        ),
    ]
