# Generated by Django 5.0.1 on 2024-04-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0055_userspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinventory',
            name='precioVentaVendedorExterno',
            field=models.FloatField(default=0, verbose_name='Precio de venta para vendedor externo'),
        ),
    ]
