# Generated by Django 5.0.1 on 2024-06-23 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0056_sellerinventory_precioventavendedorexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvinventory',
            name='precioVentaVendedorExterno',
            field=models.FloatField(default=0, verbose_name='Precio de venta para vendedor externo'),
        ),
        migrations.AddField(
            model_name='registroinventariopuntoventa',
            name='code',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='registroinventariopuntoventa',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventariovendedores',
            name='code',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='registroinventariovendedores',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=datetime.date(2024, 6, 23)),
        ),
    ]
