# Generated by Django 5.0.1 on 2024-06-23 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0057_pvinventory_precioventavendedorexterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersales',
            name='date_added',
            field=models.DateTimeField(default=datetime.date(2024, 6, 23)),
        ),
    ]
