# Generated by Django 5.0.1 on 2024-06-23 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becaanaPVm1APP1', '0058_alter_sellersales_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sellersales',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
